*: remove owner from contract storage
nspcc-dev/neofs-contract pull request #207
Opened 2021-12-27 07:48 UTC by fyrchik

Close #202 .

It is no longer used and should've be removed on update.

Signed-off-by: Evgenii Stratonikov <evgeniy@nspcc.ru>

2021-12-27 08:41 UTC, carpawell requested changes

2021-12-27 08:41 UTC, carpawell commented on container/container_contract.go
> +		storage.Delete(common.LegacyOwnerKey)
missing `ctx` arg?

2021-12-27 11:27 UTC, alexvanin commented
Rebase after https://github.com/nspcc-dev/neofs-contract/pull/206

2021-12-28 09:40 UTC, alexvanin approved these changes

2021-12-28 09:40 UTC, alexvanin commented on neofsid/neofsid_contract.go
>  		it := storage.Find(ctx, []byte{}, storage.None)
Can you drop the code below in `isUpdate` branch? It was used for `v0.13.x` update and is not related anymore.

2021-12-28 10:32 UTC, merged